# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4, 5, 6], [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[2, 3.0, 4.4],
                [7, 8.7, 5.6],
                [9.0, 3.5, 4.3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape

(3,)

In [ ]:
a1.ndim

1

In [ ]:
a1.size

3

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
# Attributes of 2-dimensional array
a2.shape

(2, 3)

In [ ]:
a2.ndim

2

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.size

6

In [ ]:
# Attributes of 3-dimensional array
a3.shape

(1, 3, 3)

In [ ]:
a3.ndim

3

In [ ]:
a3.dtype

dtype('float64')

In [ ]:
a3.size

9

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  4  5  6
1  7  8  9

In [ ]:
# Create an array of shape (10, 2) with only ones

ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros

zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3

range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

random_array = np.random.randint(0, 10, size = (7, 2))
random_array

array([[3, 9],
       [9, 2],
       [6, 3],
       [6, 8],
       [4, 6],
       [4, 7],
       [9, 2]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

np.random.random((3, 5))

array([[0.51335544, 0.94316523, 0.03409696, 0.97255914, 0.40020873],
       [0.07839764, 0.37933342, 0.21447201, 0.98054784, 0.32325228],
       [0.24818028, 0.77210935, 0.45019304, 0.1529137 , 0.2711949 ]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_4 = np.random.randint(10, size = (4, 6))
random_array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_5 = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
np.unique(random_array_5)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Find the 0'th index of the latest array you created
a1[0]

1

In [ ]:
# Get the first 2 rows of latest array you created
a2[:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
a3[:2, :2]

array([[[2. , 3. , 4.4],
        [7. , 8.7, 5.6]]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rand_array = np.random.randint(10, size = (3, 5))
ones_array = np.ones((3, 5))

In [ ]:
# Add the two arrays together

rand_array + ones_array

array([[3., 4., 2., 8., 5.],
       [5., 2., 3., 3., 9.],
       [1., 4., 9., 7., 3.]])

In [ ]:
# Create another array of ones of shape (5, 3)

ones_2 = np.ones((5, 3))

In [ ]:
# Try add the array of ones and the other most recent array together

rand_array + ones_array + ones_2

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)

ones_3 = np.ones((3, 5))

In [ ]:
# Subtract the new array of ones from the other most recent array

rand_array - ones_3

array([[ 1.,  2.,  0.,  6.,  3.],
       [ 3.,  0.,  1.,  1.,  7.],
       [-1.,  2.,  7.,  5.,  1.]])

In [ ]:
# Multiply the ones array with the latest array

rand_array * ones_3

array([[2., 3., 1., 7., 4.],
       [4., 1., 2., 2., 8.],
       [0., 3., 8., 6., 2.]])

In [ ]:
# Take the latest array to the power of 2 using '**'

rand_array ** 2

array([[ 4,  9,  1, 49, 16],
       [16,  1,  4,  4, 64],
       [ 0,  9, 64, 36,  4]])

In [ ]:
# Do the same thing with np.square()

np.square(rand_array)

array([[ 4,  9,  1, 49, 16],
       [16,  1,  4,  4, 64],
       [ 0,  9, 64, 36,  4]])

In [ ]:
# Find the mean of the latest array using np.mean()

np.mean(rand_array)

3.533333333333333

In [ ]:
# Find the maximum of the latest array using np.max()

np.max(rand_array)

8

In [ ]:
# Find the minimum of the latest array using np.min()

np.min(rand_array)

0

In [ ]:
# Find the standard deviation of the latest array

np.std(rand_array)

2.85657137141714

In [ ]:
# Find the variance of the latest array

np.var(rand_array)

8.16

In [ ]:
# Reshape the latest array to (3, 5, 1)

rand_array.reshape(3, 5, 1)

array([[[3],
        [2],
        [6],
        [2],
        [3]],

       [[2],
        [3],
        [5],
        [0],
        [5]],

       [[9],
        [0],
        [3],
        [7],
        [4]]])

In [ ]:
# Transpose the latest array

a3.T

array([[[2. ],
        [7. ],
        [9. ]],

       [[3. ],
        [8.7],
        [3.5]],

       [[4.4],
        [5.6],
        [4.3]]])

In [ ]:
a3.shape

(1, 3, 3)

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

np.random.seed(0)

x = np.random.randint(10, size = (3, 3))
y = np.random.randint(10, size = (3, 2))

In [ ]:
# Perform a dot product on the two newest arrays you created

x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [ ]:
y

array([[4, 7],
       [6, 8],
       [8, 1]])

In [ ]:
np.dot(x, y)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

a = np.random.randint(10, size = (4, 3))
b = np.random.randint(10, size = (4, 3))

In [ ]:
# Perform a dot product on the two newest arrays you created

np.dot(a, b)

ValueError: ignored

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(a.T, b)

array([[ 23,  19,  34],
       [ 62,  85,  79],
       [ 85, 129, 136]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

a1 = np.random.randint(10, size = (3, 5))
a2 = np.random.randint(10, size = (3, 5))

In [ ]:
# Compare the two arrays with '>'

a1 > a2

array([[ True,  True,  True, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='

a1 >= a2

array([[ True,  True,  True, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [ ]:
# Find which elements of the first array are greater than 7

a1 > 7

array([[False,  True,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')

a1 == a2

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order

np.sort(a1)

array([[3, 6, 7, 9, 9],
       [0, 2, 3, 5, 7],
       [4, 4, 4, 6, 9]])

In [ ]:
# Sort the indexes of one of the arrays you just created

np.argsort(a1)

array([[3, 4, 0, 1, 2],
       [2, 1, 3, 4, 0],
       [1, 2, 4, 3, 0]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(a1)

1

In [ ]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(a1)

7

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(a1, axis = 1)

array([1, 0, 0])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(a1, axis = 0)

array([0, 1, 1, 0, 2])

In [ ]:
# Create an array of normally distributed random numbers

np.random.randn(10, 15)

array([[ 1.50944508e+00,  1.06777513e+00, -6.86589477e-01,
         1.48733161e-02, -3.75665896e-01, -3.82236374e-02,
         3.67974474e-01, -4.47237002e-02, -3.02375133e-01,
        -2.22440360e+00,  7.24006359e-01,  3.59002764e-01,
         1.07612104e+00,  1.92140834e-01,  8.52925958e-01],
       [ 1.83571826e-02,  4.28303567e-01,  9.96277835e-01,
        -4.91149656e-01,  7.12678166e-01,  1.11334035e+00,
        -2.15367459e+00, -4.16111482e-01, -1.07089699e+00,
         2.21138805e-01, -1.12305712e+00, -1.05075796e+00,
         1.01207905e+00,  1.54371643e+00, -4.02114889e-01],
       [ 8.64749101e-01, -2.26869227e-01,  8.11160270e-01,
         2.87794613e-01, -5.38468160e-01,  1.90846210e+00,
        -4.75776001e-01,  1.44073112e+00, -1.14907568e+00,
         8.05714552e-01,  1.75610703e+00,  9.72979914e-01,
        -1.55111911e+00,  1.91143478e-01,  1.60477607e+00],
       [-1.42002593e+00, -2.44378268e+00, -2.05633855e+00,
        -9.92257550e-01,  1.01128532e+00,  1.40044008

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.